function out = dyn(sys, x, u)
%DYN
%    OUT = DYN(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    15-Sep-2020 22:32:03

m = sys.m;
I = sys.I;
d = sys.d;
df = sys.df;
l0 = sys.l0;
g = sys.g;

x1 = x(1, :);
x2 = x(2, :);
x3 = x(3, :);
x4 = x(4, :);
x5 = x(5, :);
x6 = x(6, :);

u1 = u(1, :);
u2 = u(2, :);
u3 = u(3, :);
u4 = u(4, :);

t2 = cos(x2);
t3 = sin(x2);
l2 = sqrt((x1.*t2 + df).^2 + (x1.*t3).^2);
contact1 = x1 <= l0;
contact2 = l2 <= l0;
u1 = u1.*contact1;
u2 = u2.*contact2;
u3 = u3.*contact1;
u4 = u4.*contact2;

t4 = df.^2;
t5 = x1.^2;
t8 = 1.0./m;
t9 = -x5;
t10 = 1.0./x1;
t6 = t2.^2;
t7 = t2.*x1;
t13 = t9+x2;
t11 = df.*t7.*2.0;
t12 = df+t7;
t14 = cos(t13);
t15 = sin(t13);
t16 = t6-1.0;
t17 = t4+t5+t11;
t18 = 1.0./t17;
t19 = 1.0./sqrt(t17);
t20 = t12.*t19;
t22 = t5.*t16.*t18;
t21 = acos(t20);
t24 = -t22;
t23 = -t21;
t26 = sqrt(t24);
t25 = t23+x5;
out = [t2.*x3+t3.*x4+d.*t14.*x6;
       -t10.*(-t2.*x4+t3.*x3+d.*t15.*x6);
       t8.*(t2.*u1+t20.*u2+t3.*t10.*u3+t19.*t26.*u4);
       -g+t8.*(t3.*u1+t26.*u2-t2.*t10.*u3-t12.*t18.*u4);
       x6;
       (u3+u4+d.*u2.*cos(t25)+d.*t14.*u1+d.*t10.*t15.*u3-d.*t19.*u4.*sin(t25))./I];
end
