function out = dynx(sys,x,u)
%DYNX
%    OUT = DYNX(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    15-Sep-2020 22:32:09

m = sys.m;
I = sys.I;
d = sys.d;
df = sys.df;
l0 = sys.l0;

x1 = x(1, :);
x2 = x(2, :);
x3 = x(3, :);
x4 = x(4, :);
x5 = x(5, :);
x6 = x(6, :);

t2 = cos(x2);
t3 = sin(x2);
l2 = sqrt((x1.*t2 + df).^2 + (x1.*t3).^2);
contact1 = x1 <= l0;
contact2 = l2 <= l0;
u1 = u(1, :).*contact1;
u2 = u(2, :).*contact2;
u3 = u(3, :).*contact1;
u4 = u(4, :).*contact2;

t4 = df.^2;
t5 = x1.*2.0;
t6 = x2.*2.0;
t7 = x1.^2;
t12 = 1.0./I;
t16 = 1.0./m;
t17 = -x5;
t18 = 1.0./x1;
t8 = t2.^2;
t9 = sin(t6);
t10 = t3.^2;
t11 = df.*t2;
t13 = t2.*x1;
t14 = t2.*x4;
t15 = t3.*x3;
t19 = 1.0./t7;
t21 = t3.*t5;
t26 = t17+x2;
t20 = t11.*2.0;
t22 = df.*t9;
t23 = t5.*t11;
t24 = df+t13;
t25 = t11+x1;
t27 = cos(t26);
t28 = sin(t26);
t29 = t8-1.0;
t30 = t5+t20;
t31 = d.*t28.*u1;
t32 = d.*t28.*x6;
t33 = t21+t22;
t34 = t4+t7+t23;
t35 = d.*t18.*t27.*u3;
t36 = 1.0./t34;
t38 = sqrt(t34);
t37 = t36.^2;
t39 = 1.0./t38;
t42 = -t38;
t45 = t7.*t29.*t36;
t40 = t39.^3;
t41 = t39.^5;
t43 = t24.*t39;
t47 = -t45;
t44 = acos(t43);
t51 = sqrt(t47);
t46 = -t44;
t53 = 1.0./t51;
t48 = t46+x5;
t49 = cos(t48);
t50 = sin(t48);
t52 = d.*t50;
t54 = t42+t52;

out = zeros(size(x, 1), size(x, 1), size(x, 2));
out(2,1,:) = t19.*(-t14+t15+t32);
out(3,1,:) = -t16.*(t40.*u2.*(df.*x1+t2.*t4+t2.*t7+df.*t8.*x1)+t3.*t19.*u3-t2.*t39.*u2+(t30.*t40.*t51.*u4)./2.0-df.*t10.*t24.*t41.*t53.*u4.*x1);
out(4,1,:) = t16.*(t2.*t19.*u3-t2.*t36.*u4+t24.*t30.*t37.*u4+df.*t10.*t24.*t37.*t53.*u2.*x1);
out(6,1,:) = -t12.*(-t18.*u3+t19.*u3.*(x1+d.*t28)-t39.*u4.*(t25.*t39-d.*df.*t29.*t40.*t49.*t53.*x1)+(t30.*t40.*u4.*(t38-t52))./2.0+df.*t29.*t40.*t52.*t53.*u2.*x1);

out(1,2,:) = t14-t15-t32;
out(2,2,:) = -t18.*(t2.*x3+t3.*x4+d.*t27.*x6);
out(3,2,:) = t16.*(-t3.*u1+t2.*t18.*u3-t3.*t39.*u2.*x1+(df.*t40.*u2.*x1.*(df.*t3.*2.0+t9.*x1))./2.0+df.*t3.*t40.*t51.*u4.*x1+t3.*t7.*t24.*t25.*t41.*t53.*u4);
out(4,2,:) = t16.*(t2.*u1+t3.*t18.*u3+t3.*t36.*u4.*x1-df.*t3.*t24.*t37.*u4.*x1.*2.0+t3.*t7.*t24.*t25.*t37.*t53.*u2);
out(6,2,:) = t12.*(-t31+t35-t39.*u4.*(df.*t3.*t39.*x1-(d.*t7.*t33.*t40.*t49.*t53)./2.0)+(t7.*t33.*t40.*t52.*t53.*u2)./2.0+df.*t3.*t40.*u4.*x1.*(t38-t52));

out(1,3,:) = t2;
out(2,3,:) = -t3.*t18;

out(1,4,:) = t3;
out(2,4,:) = t2.*t18;

out(1,5,:) = t32;
out(2,5,:) = d.*t18.*t27.*x6;
out(6,5,:) = -t12.*(-t31+t35+t52.*u2+d.*t39.*t49.*u4);

out(1,6,:) = d.*t27;
out(2,6,:) = -d.*t18.*t28;
out(5,6,:) = ones(1, 1, size(x,2));

end
