function out = dynuu(sys, x, u)
%DYNXU
%    OUT = DYNUU(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Sep-2020 12:58:59

out = zeros(size(x,1), size(u,1), size(u,1), size(x,2)); % System is control affine
end
