function out = dyn(sys, x, u)
%DYN
%    OUT1 = DYN(I1,I2,I3,BK,G,L,M,U1,U2,U3,U4,X2,X3,X4,X7,X8,X9,X10)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Aug-2021 14:39:40

m = sys.m;
l = sys.l;
g = sys.g;
bk = sys.bk;
I1 = sys.I(1, 1);
I2 = sys.I(2, 2);
I3 = sys.I(3, 3);
X_DIMS_FREE = sys.X_DIMS_FREE; % Assuming they are sorted

x2 = x{2};
x3 = x{3};
x4 = x{4};
x7 = x{7};
x8 = x{8};
x9 = x{9};
x10 = x{10};

u1 = u{1};
u2 = u{2};
u3 = u{3};
u4 = u{4};

t2 = cos(x2);
t3 = cos(x3);
t4 = cos(x4);
t5 = sin(x2);
t6 = sin(x3);
t7 = sin(x4);
t8 = I1.^2;
t9 = I2.^2;
t10 = I3.^2;
t11 = x2.*2.0;
t12 = x3.*2.0;
t13 = x9.^2;
t14 = x10.^2;
t21 = 1.0./I2;
t22 = 1.0./I3;
t23 = 1.0./m;
t15 = t2.^2;
t16 = t3.^2;
t17 = t3.^3;
t18 = sin(t11);
t19 = sin(t12);
t20 = t5.^2;
t24 = 1.0./t3;
t25 = 1.0./t16;
et1 = I1.*t10.*x9.*x10-I3.*t8.*x9.*x10+I1.*I2.*I3.*x9.*x10+I2.*I3.*l.*t3.*u2-I1.*t6.*t10.*x8.*x9+I3.*t6.*t8.*x8.*x9+I1.*t9.*t15.*x9.*x10-I2.*t8.*t15.*x9.*x10-I1.*t10.*t15.*x9.*x10+I3.*t8.*t15.*x9.*x10-I1.*t10.*t16.*x9.*x10+I3.*t8.*t16.*x9.*x10+I2.*t10.*t16.*x9.*x10-I3.*t9.*t16.*x9.*x10+I1.*I2.*I3.*t16.*x8.*x9+I1.*I2.*bk.*t2.*t6.*u4+I1.*I3.*l.*t5.*t6.*u3+I1.*t2.*t3.*t5.*t9.*t14-I2.*t2.*t3.*t5.*t8.*t14-I1.*t2.*t3.*t5.*t10.*t14+I2.*t2.*t3.*t5.*t10.*t13+I3.*t2.*t3.*t5.*t8.*t14-I3.*t2.*t3.*t5.*t9.*t13-I1.*t2.*t5.*t9.*t14.*t17+I2.*t2.*t5.*t8.*t14.*t17+I1.*t2.*t5.*t10.*t14.*t17-I3.*t2.*t5.*t8.*t14.*t17;
et2 = -I2.*t2.*t5.*t10.*t14.*t17+I3.*t2.*t5.*t9.*t14.*t17-I1.*t6.*t9.*t15.*x8.*x9+I2.*t6.*t8.*t15.*x8.*x9+I1.*t6.*t10.*t15.*x8.*x9-I3.*t6.*t8.*t15.*x8.*x9-I1.*t9.*t15.*t16.*x9.*x10+I2.*t8.*t15.*t16.*x9.*x10+I1.*t10.*t15.*t16.*x9.*x10-I3.*t8.*t15.*t16.*x9.*x10-I2.*t10.*t15.*t16.*x9.*x10.*2.0+I3.*t9.*t15.*t16.*x9.*x10.*2.0+I1.*I2.*I3.*t6.*t15.*x8.*x9-I1.*I2.*I3.*t15.*t16.*x8.*x9-I1.*I2.*I3.*t2.*t5.*t17.*x8.*x10-I1.*t2.*t3.*t5.*t6.*t9.*x8.*x10+I2.*t2.*t3.*t5.*t6.*t8.*x8.*x10+I1.*t2.*t3.*t5.*t6.*t10.*x8.*x10-I3.*t2.*t3.*t5.*t6.*t8.*x8.*x10+I1.*I2.*I3.*t2.*t3.*t5.*t6.*x8.*x10;
mt2 = t21.*t22.*(t9.*t14.*t19-t3.*t9.*x8.*x10.*2.0-t9.*t18.*x8.*x9+t10.*t18.*x8.*x9-I1.*I2.*t14.*t19+I2.*bk.*t5.*u4.*2.0-I3.*l.*t2.*u3.*2.0+I1.*I2.*t3.*x8.*x10.*2.0+I2.*I3.*t3.*x8.*x10.*2.0+I1.*I2.*t18.*x8.*x9-I1.*I3.*t18.*x8.*x9-t3.*t6.*t9.*t14.*t15.*2.0+t3.*t6.*t10.*t14.*t15.*2.0+t3.*t9.*t15.*x8.*x10.*2.0-t3.*t10.*t15.*x8.*x10.*2.0+t2.*t5.*t6.*t9.*x9.*x10.*2.0-t2.*t5.*t6.*t10.*x9.*x10.*2.0+I1.*I2.*t3.*t6.*t14.*t15.*2.0-I1.*I3.*t3.*t6.*t14.*t15.*2.0-I1.*I2.*t3.*t15.*x8.*x10.*2.0+I1.*I3.*t3.*t15.*x8.*x10.*2.0-I1.*I2.*t2.*t5.*t6.*x9.*x10.*2.0+I1.*I3.*t2.*t5.*t6.*x9.*x10.*2.0).*(-1.0./2.0);
mt3 = t25.*(t5.*x9-t2.*t3.*x10).*(t3.*t5.*x8-t2.*t6.*x9)+t21.*t22.*t24.*(-t9.*t15.*x8.*x9-t10.*t20.*x8.*x9+I2.*bk.*t2.*u4+I3.*l.*t5.*u3+I1.*I2.*t15.*x8.*x9+I1.*I3.*t20.*x8.*x9+t6.*t9.*t15.*x9.*x10+t6.*t10.*t20.*x9.*x10+t2.*t3.*t5.*t6.*t9.*t14-t2.*t3.*t5.*t6.*t10.*t14-t2.*t3.*t5.*t9.*x8.*x10+t2.*t3.*t5.*t10.*x8.*x10-I1.*I2.*t6.*t15.*x9.*x10-I1.*I3.*t6.*t20.*x9.*x10-I1.*I2.*t2.*t3.*t5.*t6.*t14+I1.*I3.*t2.*t3.*t5.*t6.*t14+I1.*I2.*t2.*t3.*t5.*x8.*x10-I1.*I3.*t2.*t3.*t5.*x8.*x10)+t25.*x8.*cos(x2-x3).*(t2.*x9+t3.*t5.*x10);

out = cell(length(X_DIMS_FREE), 1);
for xxi=1:1:length(X_DIMS_FREE)
    xx = X_DIMS_FREE(xxi);
    if (xx==1)
        out{xxi} = x7;
    elseif (xx==2)
        out{xxi} = x8;
    elseif (xx==3)
        out{xxi} = x9;
    elseif (xx==4)
        out{xxi} = x10;
    elseif (xx==5)
        out{xxi} = t23.*u1.*(t5.*t7+t2.*t4.*t6);
    elseif (xx==6)
        out{xxi} = -t23.*u1.*(t4.*t5-t2.*t6.*t7);
    elseif (xx==7)
        out{xxi} = -g+t2.*t3.*t23.*u1;
    elseif (xx==8)
        out{xxi} = (t21.*t22.*t24.*(et1+et2))./I1;
    elseif (xx==9)
        out{xxi} = mt2;
    elseif (xx==10)
        out{xxi} = mt3;
    end
end
end
