function out = dynu(sys, x, u)
%DYNU
%    OUT1 = DYNU(I1,I2,I3,BK,L,M,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    13-Aug-2021 14:39:43

m = sys.m;
l = sys.l;
bk = sys.bk;
I1 = sys.I(1, 1);
I2 = sys.I(2, 2);
I3 = sys.I(3, 3);

x2 = x(2, :);
x3 = x(3, :);
x4 = x(4, :);

t2 = cos(x2);
t3 = cos(x3);
t4 = cos(x4);
t5 = sin(x2);
t6 = sin(x3);
t7 = sin(x4);
t8 = 1.0./I2;
t9 = 1.0./I3;
t10 = 1.0./m;
t11 = 1.0./t3;

out = zeros(size(x, 1), size(u, 1), size(x, 2));

out(5:7,1,:) = [t10.*(t5.*t7+t2.*t4.*t6);
                -t10.*(t4.*t5-t2.*t6.*t7);
                t2.*t3.*t10];

out(8,2,:) = l./I1;

out(8:10,3,:) = [l.*t5.*t6.*t8.*t11;
                 l.*t2.*t8;
                 l.*t5.*t8.*t11];

out(8:10,4,:) = [bk.*t2.*t6.*t9.*t11;
                 -bk.*t5.*t9;
                 bk.*t2.*t9.*t11];
end
