function out = CN(sys, x, u)
%CN
%    OUT = CN(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    19-Oct-2020 18:29:06
l1 = sys.l(1);
l2 = sys.l(2);
l3 = sys.l(3);
l4 = sys.l(4);

m1 = sys.m(1);
m2 = sys.m(2);
m3 = sys.m(3);
m4 = sys.m(4);

g = sys.g;

th1 = x(1,:);
th2 = x(2,:);
th3 = x(3,:);
th4 = x(4,:);

dth1 = x(5,:);
dth2 = x(6,:);
dth3 = x(7,:);
dth4 = x(8,:);

t2 = sin(th1);
t3 = sin(th2);
t4 = sin(th3);
t5 = sin(th4);
t6 = th1+th2;
t7 = th2+th3;
t8 = th3+th4;
t9 = dth1.^2;
t10 = dth2.^2;
t11 = dth3.^2;
t12 = dth4.^2;
t13 = sin(t6);
t14 = sin(t7);
t15 = sin(t8);
t16 = t6+th3;
t17 = t7+th4;
t20 = t6+t8;
t22 = dth1.*dth3.*l2.*l3.*m3.*t4;
t23 = dth2.*dth3.*l2.*l3.*m3.*t4;
t24 = dth1.*dth4.*l3.*l4.*m4.*t5;
t25 = dth2.*dth4.*l3.*l4.*m4.*t5;
t26 = dth3.*dth4.*l3.*l4.*m4.*t5;
t29 = l2.*l3.*m4.*t4.*t11;
t30 = dth1.*dth3.*l2.*l3.*m4.*t4.*2.0;
t31 = dth2.*dth3.*l2.*l3.*m4.*t4.*2.0;
t53 = (l2.*l3.*m3.*t4.*t11)./2.0;
t54 = (l3.*l4.*m4.*t5.*t12)./2.0;
t18 = sin(t16);
t19 = sin(t17);
t21 = sin(t20);
t27 = g.*l2.*m3.*t13;
t28 = g.*l2.*m4.*t13;
t33 = dth1.*dth3.*l2.*l4.*m4.*t15;
t34 = dth1.*dth4.*l2.*l4.*m4.*t15;
t35 = dth2.*dth3.*l2.*l4.*m4.*t15;
t36 = dth2.*dth4.*l2.*l4.*m4.*t15;
t37 = dth3.*dth4.*l2.*l4.*m4.*t15;
t38 = -t22;
t39 = -t23;
t40 = -t30;
t41 = -t31;
t42 = -t24;
t43 = -t25;
t44 = -t26;
t45 = l1.*l3.*m4.*t9.*t14;
t46 = -t29;
t47 = (g.*l2.*m2.*t13)./2.0;
t57 = -t53;
t58 = -t54;
t59 = (l1.*l3.*m3.*t9.*t14)./2.0;
t60 = (l2.*l4.*m4.*t11.*t15)./2.0;
t61 = (l2.*l4.*m4.*t12.*t15)./2.0;
t32 = g.*l3.*m4.*t18;
t48 = -t33;
t49 = -t34;
t50 = -t35;
t51 = -t36;
t52 = -t37;
t55 = (g.*l3.*m3.*t18)./2.0;
t56 = (g.*l4.*m4.*t21)./2.0;
t62 = -t60;
t63 = -t61;
t64 = (l1.*l4.*m4.*t9.*t19)./2.0;

out = zeros(4, 1, size(x, 2));

out(1,1,:) = t27+t28+t32+t38+t39+t40+t41+t42+t43+t44+t46+t47+t48+t49+t50+t51+t52+t55+t56+t57+t58+t62+t63+(g.*l1.*m1.*t2)./2.0+g.*l1.*m2.*t2+g.*l1.*m3.*t2+g.*l1.*m4.*t2-(l1.*l2.*m2.*t3.*t10)./2.0-l1.*l2.*m3.*t3.*t10-l1.*l2.*m4.*t3.*t10-(l1.*l3.*m3.*t10.*t14)./2.0-(l1.*l3.*m3.*t11.*t14)./2.0-l1.*l3.*m4.*t10.*t14-l1.*l3.*m4.*t11.*t14-(l1.*l4.*m4.*t10.*t19)./2.0-(l1.*l4.*m4.*t11.*t19)./2.0-(l1.*l4.*m4.*t12.*t19)./2.0-dth1.*dth2.*l1.*l2.*m2.*t3-dth1.*dth2.*l1.*l2.*m3.*t3.*2.0-dth1.*dth2.*l1.*l2.*m4.*t3.*2.0-dth1.*dth2.*l1.*l3.*m3.*t14-dth1.*dth2.*l1.*l3.*m4.*t14.*2.0-dth1.*dth3.*l1.*l3.*m3.*t14-dth1.*dth3.*l1.*l3.*m4.*t14.*2.0-dth2.*dth3.*l1.*l3.*m3.*t14-dth2.*dth3.*l1.*l3.*m4.*t14.*2.0-dth1.*dth2.*l1.*l4.*m4.*t19-dth1.*dth3.*l1.*l4.*m4.*t19-dth1.*dth4.*l1.*l4.*m4.*t19-dth2.*dth3.*l1.*l4.*m4.*t19-dth2.*dth4.*l1.*l4.*m4.*t19-dth3.*dth4.*l1.*l4.*m4.*t19;
out(2,1,:) = t27+t28+t32+t38+t39+t40+t41+t42+t43+t44+t45+t46+t47+t48+t49+t50+t51+t52+t55+t56+t57+t58+t59+t62+t63+t64+(l1.*l2.*m2.*t3.*t9)./2.0+l1.*l2.*m3.*t3.*t9+l1.*l2.*m4.*t3.*t9;
out(3,1,:) = t32+t42+t43+t44+t45+t55+t56+t58+t59+t64+(l2.*l3.*m3.*t4.*t9)./2.0+(l2.*l3.*m3.*t4.*t10)./2.0+l2.*l3.*m4.*t4.*t9+l2.*l3.*m4.*t4.*t10+(l2.*l4.*m4.*t9.*t15)./2.0+(l2.*l4.*m4.*t10.*t15)./2.0+dth1.*dth2.*l2.*l3.*m3.*t4+dth1.*dth2.*l2.*l3.*m4.*t4.*2.0+dth1.*dth2.*l2.*l4.*m4.*t15;
out(4,1,:) = (l4.*m4.*(g.*t21+l3.*t5.*t9+l3.*t5.*t10+l3.*t5.*t11+l2.*t9.*t15+l2.*t10.*t15+l1.*t9.*t19+dth1.*dth2.*l3.*t5.*2.0+dth1.*dth3.*l3.*t5.*2.0+dth2.*dth3.*l3.*t5.*2.0+dth1.*dth2.*l2.*t15.*2.0))./2.0;

end
