function out = dynu(sys, x, u)
%DYNU
%    OUT = DYNU(SYS,X,U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Sep-2020 19:09:33

mc = sys.mc;
mp = sys.mp;
l = sys.l;

x3 = x(3,:);

t2 = cos(x3);
t3 = sin(x3);
t5 = 1.0./l;
t4 = t3.^2;
t6 = mp.*t4;
t7 = mc+t6;
t8 = 1.0./t7;
t9 = t2.*t5.*t8;
t10 = -t9;

out = zeros(size(x, 1), size(u, 1), size(x, 2));
out(2, 1, :) = t8;
out(4, 1, :) = t10;
out(2, 2, :) = t10;
out(4, 2, :) = t5.^2.*t8.*(mc./mp+1.0);

end