function out = dynx(sys, x, u)
%DYNX
%    OUT = DYNX(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Sep-2020 19:09:33

mc = sys.mc;
mp = sys.mp;
l = sys.l;
g = sys.g;

x3 = x(3,:);
x4 = x(4,:);

u1 = u(1,:);
u2 = u(2,:);

t2 = cos(x3);
t3 = sin(x3);
t4 = mc+mp;
t5 = l.^2;
t6 = mp.^2;
t7 = x4.^2;
t10 = 1.0./l;
t8 = t2.^2;
t9 = t3.^2;
t11 = mp.*t9;
t12 = mc+t11;
t13 = 1.0./t12;
t14 = t13.^2;

out = zeros(size(x, 1), size(x, 1), size(x, 2));

out(1, 2, :) = ones(1,1,size(x, 2));
out(2, 3, :) = t10.*t14.*(mp.*t3.^3.*u2+mc.*t3.*u2-g.*l.*mc.*mp-g.*l.*t6.*t9+mp.*t3.*t8.*u2.*2.0+g.*l.*mc.*mp.*t8.*2.0-l.*mp.*t2.*t3.*u1.*2.0+mc.*mp.*t2.*t5.*t7-t2.*t5.*t6.*t7.*t9);
out(4, 3, :) = -t10.*t13.*(g.*t2.*t4+l.*mp.*t7.*(t8.*2.0-1.0))+t3.*t10.*t13.*u1+mp.*t2.*t3.*t10.*t14.*(g.*t3.*t4+l.*mp.*t2.*t3.*t7).*2.0+mp.*t2.*t3.*t10.*t14.*(t2.*u1-t10.*u2.*(mc./mp+1.0)).*2.0;
out(2, 4, :) = l.*mp.*t3.*t13.*x4.*2.0;
out(3, 4, :) = ones(1,1,size(x, 2));
out(4, 4, :) = -mp.*t13.*x4.*sin(x3.*2.0);

end
