function out = dynxu(sys, x, u)
%DYNXU
%    OUT = DYNXU(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Sep-2020 12:58:59

mc = sys.mc;
mp = sys.mp;
l = sys.l;

x3 = x(3,:);

t2 = cos(x3);
t3 = sin(x3);
t4 = mp.*2.0;
t6 = 1.0./l;
t5 = t3.^2;
t7 = mp.*t5;
t8 = -t7;
t9 = mc+t7;
t10 = 1.0./t9.^2;
t11 = mc+t4+t8;
t12 = t3.*t6.*t10.*t11;

out = zeros(size(x,1), size(x,1), size(u,1), size(x,2));

out(2,3,1,:) = mp.*t2.*t3.*t10.*-2.0;
out(4,3,1,:) = t12;

out(2,3,2,:) = t12;
out(4,3,2,:) = t2.*t3.*t6.^2.*t10.*(mc+mp).*-2.0;

end
