function out = dynu(sys, x, u)
%DYNU
%    OUT = DYNU(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    21-Sep-2020 10:14:12

m1 = sys.m(1);
m2 = sys.m(2);
l1 = sys.l(1);
l2 = sys.l(2);

th2 = x(2,:);

t2 = cos(th2);
t3 = l1.^2;
t4 = m1.*4.0;
t7 = 1.0./l2;
t8 = m2.*1.2e+1;
t5 = t2.^2;
t6 = 1.0./t3;
t9 = m2.*t5.*9.0;
t10 = -t9;
t11 = t4+t8+t10;
t12 = 1.0./t11;

out = zeros(size(x,1), size(u,1), size(x,2));

out(3,1,:) = t6.*t12.*1.2e+1;
out(4,1,:) = -t6.*t7.*t12.*(l2.*1.2e+1+l1.*t2.*1.8e+1);

out(3,2,:) = t6.*t7.*t12.*(l2.*4.0+l1.*t2.*6.0).*-3.0;
out(4,2,:) = (t6.*t7.^2.*t12.*(t3.*t4+t3.*t8+m2.*1.0./t7.^2.*4.0+l1.*l2.*t2.*t8).*3.0)./m2;

end
