function fx = fx_CartPoleFirst(sys, x, u)
%FX_CARTPOLE
%    FX = FX_CARTPOLE(G,L,MC,MP,U1,U2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Mar-2020 14:08:02
mc = sys.mc;
mp = sys.mp;
l = sys.l;
g = sys.g;
l_point = sys.l_point;

U_DIMS_FREE = sys.U_DIMS_FREE;
U = zeros(2, size(u, 2));
% lims = sys.lims(U_DIMS_FREE,:);
% U(U_DIMS_FREE, :) = max(lims(:,1)*ones(1,size(u,2)), ...
%                         min(lims(:,2)*ones(1,size(u,2)), u));
U(U_DIMS_FREE, :) = u; 
u1 = U(1, :);
u2 = U(2, :);

X_DIMS_FREE = sys.X_DIMS_FREE;
X_DIMS_FIXED = sys.X_DIMS_FIXED;
% X_DIMS_FIXED = linspace(1,4,4)';
% X_DIMS_FIXED(X_DIMS_FREE) = [];
X = zeros(4, size(x, 2));
X(X_DIMS_FREE, :) = x;
X(X_DIMS_FIXED, :) = repmat(l_point(X_DIMS_FIXED), [1, size(x,2)]);
x1 = X(1, :);
x2 = X(2, :);
x3 = X(3, :);
x4 = X(4, :);

t2 = cos(x3);
t3 = sin(x3);
t4 = mc+mp;
t5 = x3.*2.0;
t6 = x4.^2;
t10 = 1.0./l;
t7 = cos(t5);
t8 = sin(t5);
t9 = t3.^2;
t11 = mp.*t9;
t12 = mc+t11;
t13 = 1.0./t12;
t14 = t13.^2;

fx = zeros(4, 4, size(x, 2));
fx(1,2,:) = ones(1, 1, size(x, 2));
fx(3,4,:) = ones(1, 1, size(x, 2));
fx(2,3,:) = t13.*(g.*mp.*t7+l.*mp.*t2.*t6)+t3.*t10.*t13.*u2-mp.*t2.*t3.*t14.*((g.*mp.*t8)./2.0+l.*mp.*t3.*t6).*2.0-mp.*t2.*t3.*t14.*(u1-t2.*t10.*u2).*2.0;
fx(2,4,:) = l.*mp.*t3.*t13.*x4.*2.0;
fx(4,3,:) = -t10.*t13.*(g.*t2.*t4+l.*mp.*t6.*t7)+t3.*t10.*t13.*u1+mp.*t2.*t3.*t10.*t14.*(t2.*u1-t10.*u2.*(mc./mp+1.0)).*2.0+mp.*t2.*t3.*t10.*t14.*(g.*t3.*t4+(l.*mp.*t6.*t8)./2.0).*2.0;
fx(4,4,:) = -mp.*t8.*t13.*x4;

fx = fx(X_DIMS_FREE, :, :);
fx = fx(:, X_DIMS_FREE, :);
end



