function out = interpn_gpu(varargin)
%% Inputs
% x1, ... xn
% V
% xi1, ... xin

n = (length(varargin) - 1) / 2; % 2n + 1
assert(n == round(n), 'Check the number of inputs');

x  = varargin(1:n);
V  = varargin{n+1};
xi = varargin((n+2):(2*n+1));

Nx = size(x{1}); % Number of grid points in each dimension
x1 = cellfun(@(y) y(1), x); % Min value in each dimension
dx = cellfun(@(y) y(end) - y(1), x) ./ (Nx - 1); % Discretizatio in each dimension

% Generate corners of the n dimensional hyper-cube
corners = 0:1:(2^n - 1);
cb = zeros(n, 2^n);
for ii=1:1:n
    r = floor(corners / 2);
    cb(ii, :) = corners - 2*r;
    corners = r;
end
cb = num2cell(flip(cb + 1, 1), 2);
corners_index = sub2ind(Nx, cb{:}) - 1;

if (n==1)
   out = arrayfun(@calc_average1, xi{:});
%     out = calc_average1(xi{:});
elseif (n==2)
   out = arrayfun(@calc_average2, xi{:});
%     out = calc_average2(xi{:});
elseif (n==3)
   out = arrayfun(@calc_average3, xi{:});
%     out = calc_average3(xi{:});
elseif (n==4)
   out = arrayfun(@calc_average4, xi{:});
%     out = calc_average4(xi{:});
elseif (n==5)
   out = arrayfun(@calc_average5, xi{:});
%     out = calc_average5(xi{:});
elseif (n==6)
   out = arrayfun(@calc_average6, xi{:});
%     out = calc_average6(xi{:});
elseif (n==7)
   out = arrayfun(@calc_average7, xi{:});
%     out = calc_average7(xi{:});
elseif (n==8)
   out = arrayfun(@calc_average8, xi{:});
%     out = calc_average8(xi{:});
end

%% GPU functions for different 'n'

    function average_value = calc_average1(Xi1)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        loc1 = min(Nx(1)-1, floor(Xi1));
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        scalar_loc = loc1;
        average_value = (1 - Xi1) .* V(scalar_loc + corners_index(1)) ...
                            + Xi1 .* V(scalar_loc + corners_index(2));
    end
    
    function average_value = calc_average2(Xi1, Xi2)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2; 
        
        scalar_loc = loc1 + Nx(1) * (loc2 - 1);
        
        average_value = (1 - Xi1) * ((1 - Xi2) * V(scalar_loc + corners_index(1)) ...
                                         + Xi2 * V(scalar_loc + corners_index(2))) ...
                            + Xi1 * ((1 - Xi2) * V(scalar_loc + corners_index(3)) ...
                                         + Xi2 * V(scalar_loc + corners_index(4)));
    end
    
    function average_value = calc_average3(Xi1, Xi2, Xi3)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        
        scalar_loc = loc1 + Nx(1) * ((loc2 - 1) + Nx(2) * (loc3 - 1));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* V(scalar_loc + corners_index(1)) ...
                                                  + Xi3 .* V(scalar_loc + corners_index(2))) ...
                                     + Xi2 .* ((1 - Xi3) .* V(scalar_loc + corners_index(3)) ...
                                                  + Xi3 .* V(scalar_loc + corners_index(4)))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* V(scalar_loc + corners_index(5)) ...
                                                  + Xi3 .* V(scalar_loc + corners_index(6))) ...
                                     + Xi2 .* ((1 - Xi3) .* V(scalar_loc + corners_index(7)) ...
                                                  + Xi3 .* V(scalar_loc + corners_index(8))));
    end
    
    function average_value = calc_average4(Xi1, Xi2, Xi3, Xi4)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        Xi4 = (Xi4 - x1(4)) / dx(4) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        loc4 = min(Nx(4)-1, floor(Xi4));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        Xi4 = Xi4 - loc4;
        
        scalar_loc = loc1 + Nx(1) * ((loc2 - 1) + Nx(2) * ((loc3 - 1) + Nx(3) * (loc4 - 1)));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* V(scalar_loc + corners_index(1)) ...
                                                                + Xi4 .* V(scalar_loc + corners_index(2))) ...
                                                   + Xi3 .* ((1 - Xi4) .* V(scalar_loc + corners_index(3)) ...
                                                             + Xi4 .* V(scalar_loc + corners_index(4)))) ...
                                     + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* V(scalar_loc + corners_index(5)) ...
                                                                + Xi4 .* V(scalar_loc + corners_index(6))) ...
                                                   + Xi3 .* ((1 - Xi4) .* V(scalar_loc + corners_index(7)) ...
                                                             + Xi4 .* V(scalar_loc + corners_index(8))))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* V(scalar_loc + corners_index(9)) ...
                                                                + Xi4 .* V(scalar_loc + corners_index(10))) ...
                                                   + Xi3 .* ((1 - Xi4) .* V(scalar_loc + corners_index(11)) ...
                                                             + Xi4 .* V(scalar_loc + corners_index(12)))) ...
                                     + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* V(scalar_loc + corners_index(13)) ...
                                                                + Xi4 .* V(scalar_loc + corners_index(14))) ...
                                                   + Xi3 .* ((1 - Xi4) .* V(scalar_loc + corners_index(15)) ...
                                                             + Xi4 .* V(scalar_loc + corners_index(16)))));
    end

    function average_value = calc_average5(Xi1, Xi2, Xi3, Xi4, Xi5)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        Xi4 = (Xi4 - x1(4)) / dx(4) + 1;
        Xi5 = (Xi5 - x1(5)) / dx(5) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        loc4 = min(Nx(4)-1, floor(Xi4));
        loc5 = min(Nx(5)-1, floor(Xi5));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        Xi4 = Xi4 - loc4;
        Xi5 = Xi5 - loc5;
        
        scalar_loc = loc1 ...
                     + Nx(1) * ((loc2 - 1) ...
                                + Nx(2) * ((loc3 - 1) ...
                                            + Nx(3) * ((loc4 - 1) ...
                                                        + Nx(4) * (loc5 - 1))));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(1)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(2))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(3)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(4))))...
                                                   + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(5)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(6))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(7)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(8))))) ...
                                     + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(9)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(10))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(11)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(12))))...
                                                   + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(13)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(14))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(15)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(16)))))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(17)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(18))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(19)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(20))))...
                                                   + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(21)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(22))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(23)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(24))))) ...
                                     + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(25)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(26))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(27)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(28))))...
                                                   + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* V(scalar_loc + corners_index(29)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(30))) ...
                                                                + Xi4 .* ((1 - Xi5) .* V(scalar_loc + corners_index(31)) ...
                                                                             + Xi5 .* V(scalar_loc + corners_index(32))))));
    end
    
    function average_value = calc_average6(Xi1, Xi2, Xi3, Xi4, Xi5, Xi6)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        Xi4 = (Xi4 - x1(4)) / dx(4) + 1;
        Xi5 = (Xi5 - x1(5)) / dx(5) + 1;
        Xi6 = (Xi6 - x1(6)) / dx(6) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        loc4 = min(Nx(4)-1, floor(Xi4));
        loc5 = min(Nx(5)-1, floor(Xi5));
        loc6 = min(Nx(6)-1, floor(Xi6));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        Xi4 = Xi4 - loc4;
        Xi5 = Xi5 - loc5;
        Xi6 = Xi6 - loc6;
        
        scalar_loc = loc1 ...
                     + Nx(1) * ((loc2 - 1) ...
                                + Nx(2) * ((loc3 - 1) ...
                                            + Nx(3) * ((loc4 - 1) ...
                                                        + Nx(4) * ((loc5 - 1) ...
                                                                    + Nx(5) * (loc6 - 1)))));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(1)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(2))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(3)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(4)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(5)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(6))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(7)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(8)))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(9)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(10))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(11)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(12)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(13)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(14))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(15)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(16)))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(17)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(18))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(19)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(20)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(21)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(22))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(23)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(24)))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(25)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(26))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(27)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(28)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(29)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(30))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(31)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(32))))))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(33)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(34))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(35)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(36)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(37)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(38))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(39)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(40)))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(41)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(42))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(43)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(44)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(45)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(46))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(47)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(48)))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(49)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(50))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(51)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(52)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(53)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(54))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(55)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(56)))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(57)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(58))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(59)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(60)))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* V(scalar_loc + corners_index(61)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(62))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* V(scalar_loc + corners_index(63)) ...
                                                                                                  + Xi6 .* V(scalar_loc + corners_index(64)))))));
    end
    
    function average_value = calc_average7(Xi1, Xi2, Xi3, Xi4, Xi5, Xi6, Xi7)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        Xi4 = (Xi4 - x1(4)) / dx(4) + 1;
        Xi5 = (Xi5 - x1(5)) / dx(5) + 1;
        Xi6 = (Xi6 - x1(6)) / dx(6) + 1;
        Xi7 = (Xi7 - x1(7)) / dx(7) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        loc4 = min(Nx(4)-1, floor(Xi4));
        loc5 = min(Nx(5)-1, floor(Xi5));
        loc6 = min(Nx(6)-1, floor(Xi6));
        loc7 = min(Nx(7)-1, floor(Xi7));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        Xi4 = Xi4 - loc4;
        Xi5 = Xi5 - loc5;
        Xi6 = Xi6 - loc6;
        Xi7 = Xi7 - loc7;
        
        scalar_loc = loc1 ...
                     + Nx(1) * ((loc2 - 1) ...
                                + Nx(2) * ((loc3 - 1) ...
                                            + Nx(3) * ((loc4 - 1) ...
                                                        + Nx(4) * ((loc5 - 1) ...
                                                                    + Nx(5) * ((loc6 - 1) ...
                                                                                + Nx(6) * (loc7 - 1))))));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(1)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(2))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(3)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(4)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(5)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(6))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(7)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(8))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(9)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(10))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(11)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(12)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(13)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(14))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(15)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(16))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(17)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(18))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(19)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(20)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(21)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(22))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(23)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(24))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(25)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(26))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(27)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(28)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(29)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(30))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(31)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(32))))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(33)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(34))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(35)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(36)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(37)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(38))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(39)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(40))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(41)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(42))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(43)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(44)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(45)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(46))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(47)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(48))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(49)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(50))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(51)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(52)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(53)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(54))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(55)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(56))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(57)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(58))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(59)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(60)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(61)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(62))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(63)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(64)))))))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(65)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(66))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(67)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(68)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(69)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(70))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(71)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(72))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(73)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(74))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(75)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(76)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(77)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(78))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(79)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(80))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(81)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(82))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(83)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(84)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(85)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(86))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(87)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(88))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(89)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(90))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(91)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(92)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(93)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(94))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(95)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(96))))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(97)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(98))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(99)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(100)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(101)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(102))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(103)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(104))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(105)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(106))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(107)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(108)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(109)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(110))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(111)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(112))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(113)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(114))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(115)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(116)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(117)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(118))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(119)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(120))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(121)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(122))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(123)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(124)))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* V(scalar_loc + corners_index(125)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(126))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* V(scalar_loc + corners_index(127)) ...
                                                                                                                + Xi7 .* V(scalar_loc + corners_index(128))))))));
    end
    
    function average_value = calc_average8(Xi1, Xi2, Xi3, Xi4, Xi5, Xi6, Xi7, Xi8)
        % Xi - weight corresponding to the 0 corner
        Xi1 = (Xi1 - x1(1)) / dx(1) + 1;
        Xi2 = (Xi2 - x1(2)) / dx(2) + 1;
        Xi3 = (Xi3 - x1(3)) / dx(3) + 1;
        Xi4 = (Xi4 - x1(4)) / dx(4) + 1;
        Xi5 = (Xi5 - x1(5)) / dx(5) + 1;
        Xi6 = (Xi6 - x1(6)) / dx(6) + 1;
        Xi7 = (Xi7 - x1(7)) / dx(7) + 1;
        Xi8 = (Xi8 - x1(8)) / dx(8) + 1;
        
        loc1 = min(Nx(1)-1, floor(Xi1));
        loc2 = min(Nx(2)-1, floor(Xi2));
        loc3 = min(Nx(3)-1, floor(Xi3));
        loc4 = min(Nx(4)-1, floor(Xi4));
        loc5 = min(Nx(5)-1, floor(Xi5));
        loc6 = min(Nx(6)-1, floor(Xi6));
        loc7 = min(Nx(7)-1, floor(Xi7));
        loc8 = min(Nx(8)-1, floor(Xi8));
        
        Xi1 = Xi1 - loc1; % Weights from the 0 corner
        Xi2 = Xi2 - loc2;
        Xi3 = Xi3 - loc3;
        Xi4 = Xi4 - loc4;
        Xi5 = Xi5 - loc5;
        Xi6 = Xi6 - loc6;
        Xi7 = Xi7 - loc7;
        Xi8 = Xi8 - loc8;
        
        scalar_loc = loc1 ...
                     + Nx(1) * ((loc2 - 1) ...
                                + Nx(2) * ((loc3 - 1) ...
                                            + Nx(3) * ((loc4 - 1) ...
                                                        + Nx(4) * ((loc5 - 1) ...
                                                                    + Nx(5) * ((loc6 - 1) ...
                                                                                + Nx(6) * ((loc7 - 1) ...
                                                                                            + Nx(7) * (loc8 - 1)))))));
        
        average_value = (1 - Xi1) .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(1)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(2))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(3)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(4)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(5)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(6))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(7)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(8))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(9)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(10))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(11)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(12)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(13)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(14))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(15)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(16)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(17)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(18))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(19)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(20)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(21)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(22))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(23)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(24))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(25)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(26))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(27)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(28)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(29)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(30))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(31)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(32)))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(33)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(34))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(35)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(36)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(37)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(38))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(39)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(40))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(41)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(42))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(43)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(44)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(45)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(46))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(47)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(48)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(49)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(50))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(51)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(52)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(53)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(54))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(55)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(56))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(57)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(58))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(59)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(60)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(61)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(62))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(63)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(64)))))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(65)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(66))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(67)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(68)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(69)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(70))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(71)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(72))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(73)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(74))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(75)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(76)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(77)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(78))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(79)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(80)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(81)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(82))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(83)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(84)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(85)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(86))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(87)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(88))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(89)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(90))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(91)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(92)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(93)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(94))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(95)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(96)))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(97)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(98))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(99)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(100)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(101)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(102))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(103)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(104))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(105)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(106))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(107)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(108)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(109)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(110))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(111)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(112)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(113)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(114))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(115)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(116)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(117)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(118))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(119)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(120))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(121)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(122))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(123)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(124)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(125)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(126))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(127)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(128))))))))) ...
                            + Xi1 .* ((1 - Xi2) .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(129)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(130))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(131)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(132)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(133)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(134))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(135)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(136))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(137)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(138))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(139)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(140)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(141)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(142))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(143)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(144)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(145)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(146))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(147)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(148)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(149)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(150))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(151)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(152))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(153)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(154))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(155)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(156)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(157)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(158))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(159)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(160)))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(161)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(162))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(163)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(164)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(165)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(166))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(167)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(168))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(169)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(170))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(171)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(172)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(173)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(174))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(175)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(176)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(177)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(178))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(179)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(180)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(181)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(182))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(183)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(184))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(185)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(186))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(187)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(188)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(189)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(190))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(191)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(192)))))))) ...
                                          + Xi2 .* ((1 - Xi3) .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(193)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(194))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(195)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(196)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(197)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(198))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(199)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(200))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(201)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(202))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(203)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(204)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(205)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(206))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(207)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(208)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(209)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(210))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(211)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(212)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(213)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(214))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(215)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(216))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(217)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(218))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(219)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(220)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(221)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(222))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(223)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(224)))))))...
                                                        + Xi3 .* ((1 - Xi4) .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(225)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(226))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(227)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(228)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(229)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(230))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(231)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(232))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(233)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(234))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(235)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(236)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(237)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(238))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(239)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(240)))))) ...
                                                                      + Xi4 .* ((1 - Xi5) .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(241)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(242))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(243)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(244)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(245)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(246))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(247)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(248))))) ...
                                                                                    + Xi5 .* ((1 - Xi6) .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(249)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(250))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(251)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(252)))) ...   
                                                                                                  + Xi6 .* ((1 - Xi7) .* ((1 - Xi8) .* V(scalar_loc + corners_index(253)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(254))) ...
                                                                                                                + Xi7 .* ((1 - Xi8) .* V(scalar_loc + corners_index(255)) ...
                                                                                                                              + Xi8 .* V(scalar_loc + corners_index(256)))))))));
    end
end
