function out = dynu(sys, x, u)
%DYNU
%    dynu = DYNU(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    01-Sep-2020 19:35:47
m = sys.m;
l = sys.l;
bk = sys.bk;
I1 = sys.I(1, 1);
I2 = sys.I(2, 2);
I3 = sys.I(3, 3);

x2 = x(2, :);
x3 = x(3, :);
x4 = x(4, :);

t2 = cos(x2);
t3 = cos(x3);
t4 = cos(x4);
t5 = sin(x2);
t6 = sin(x3);
t7 = sin(x4);
t8 = 1.0./I1;
t9 = 1.0./I2;
t10 = 1.0./I3;
t11 = 1.0./m;
t12 = t4.*t6;
t13 = t6.*t7;
t14 = 1.0./t2;
t15 = I2.*bk.*t3;
t16 = I3.*l.*t2;
t17 = I3.*l.*t3;
t18 = I2.*bk.*t6;
t19 = I3.*l.*t6;
t20 = t3.*t4.*t5;
t21 = t3.*t5.*t7;
t22 = I1.*bk.*t3.*t5;
t24 = bk.*t6.*t10;
t26 = t2.*t3.*t11;
t23 = -t19;
t25 = -t21;
t27 = t15+t19;
t29 = bk.*t3.*t10.*t14;
t30 = t13+t20;
t28 = t15+t23;
t31 = -t29;
t32 = t12+t25;
t33 = t11.*t30;
t34 = t11.*t32;
t35 = -t34;

out = zeros(size(x, 1), size(u, 1), size(x, 2));
out(5:10, 1, :) = [t33;
                   t35;
                   t26;
                   t5.*t9.*t10.*t14.*t28;
                   -t9.*t10.*(t17+t18);
                   t9.*t10.*t14.*t28];
out(5:10, 2, :) = [t33;
                   t35;
                   t26;
                   -t8.*t10.*t14.*(t16+t22);
                   t24;
                   t31];
out(5:10, 3, :) = [t33;
                   t35;
                   t26;
                   t5.*t9.*t10.*t14.*t27;
                   t9.*t10.*(t17-t18);
                   t9.*t10.*t14.*t27];
out(5:10, 4, :) = [t33;
                   t35;
                   t26;
                   t8.*t10.*t14.*(t16-t22);
                   t24;
                   t31];
end
